on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        erlang: ['26']
    container:
      image: erlang:${{matrix.erlang}}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache dependencies
      uses: actions/cache@v3
      id: cache
      env:
        cache-name: rebar3
      with:
        path: |
          ~/.cache/rebar3
        key: ci-${{runner.os}}-${{env.cache-name}}-erlang_${{matrix.erlang}}-rebar3-${{hashFiles('rebar.config')}}
        restore-keys: |
          ci-${{runner.os}}-${{env.cache-name}}-erlang_${{matrix.erlang}}-rebar3-

    - name: Fetch dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: rebar3 get-deps

    - name: Compile
      run: rebar3 compile

    - name: Tests
      run: make eunit
